baseURL = 'https://weekly.ursb.me/'
languageCode = 'en-us'
title = 'Airing Weekly'
theme = "yinyang"
DefaultContentLanguage = "cn"
copyright = '本文由 Airing 创作，采用 知识共享署名4.0 国际许可协议进行许可'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "Airing"
  homepage = "https://ursb.me"

[languages]
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[params]
mainSections = ["posts"]
headTitle = "Airing Weekly"
# disqus = "joway" # disqus account name
# extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
Description = 'Log something weekly, want you can be happy.'
favicon = 'https://airing.ursb.me/image/favicon.ico'
[[params.socials]]
name = "About Me"
link = "https://me.ursb.me/about.html"
[[params.socials]]
name = "Github"
link = "https://github.com/airingursb"
postHeaderContent = ""
postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href='https://me.ursb.me'>Airing's Blog</a></p>"
extraCSSFiles = []