baseURL = 'https://weekly.ursb.me/'
languageCode = 'en-us'
title = 'Airing Weekly'
theme = "yinyang"
DefaultContentLanguage = "cn"
copyright = '本文由 Airing 创作，采用 知识共享署名4.0 国际许可协议进行许可'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'xcode'
    tabWidth = 4

[author]
  name = "Airing"
  homepage = "https://ursb.me"

[languages]
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[params]
mainSections = ["posts"]
headTitle = "Airing Weekly"
# disqus = "joway" # disqus account name
# extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
Description = 'Log something weekly, want you can be happy.'
favicon = 'https://airing.ursb.me/image/favicon.ico'
postHeaderContent = ""
postFooterContent = "<br/><br/><p>Subscribe <a target='_blank' href='https://weekly.ursb.me/index.xml'>Airing's Weekly</a></p><p>© 粤ICP备16057808号</p>"
extraCSSFiles = []

[[params.socials]]
name = "RSS"
link = "https://weekly.ursb.me/index.xml"
[[params.socials]]
name = "About Me"
link = "https://me.ursb.me/about.html"
[[params.socials]]
name = "Github"
link = "https://github.com/airingursb"
